# Configure here all informations for the plugin

randomOre: "cobblestone"

# Configure here all drops for random ore
drop:
  - "coal"
  - "iron_ore"
  - "gold_ore"
  - "diamond_ore"
  - "emerald_ore"
  - "redstone_ore"
  - "lapis_ore"